---
server:
  port: 8081
  address: localhost
  servlet:
    context-path: /
---
modules:
  frontend:
    filepath: file:D:\\development\\git_public\\mami-starters\\spring-boot-typescript-jquery-websockets\\frontend\\
---
