---
server:
  port: 8081
  address: localhost
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:mami.jks
    key-store-password: password
    key-password: password
---
management:
  server:
    port: 4444
    ssl:
      enabled: true
---
modules:
  frontend:
    filepath: file:D:\\development\\git_public\\mami-starters\\spring-boot-typescript-jquery-websockets\\frontend\\
---
